[project]
name = "hello-world"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [ ]

[project.scripts]
hello = "hello_world:hello"

[build-system]
requires = ["uv_build>=0.11.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "hello_world"
module-root = ""
